version: 2

project_name: pudl

builds:
  - id: pudl
    main: .
    binary: pudl
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X pudl/cmd.version={{.Version}}
      - -X pudl/cmd.commit={{.Commit}}
      - -X pudl/cmd.date={{.Date}}

archives:
  - id: pudl-archive
    builds:
      - pudl
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - docs/*
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge pull request"

