// Package clidocs renders docs/cli-reference.md from the cobra command tree.
//
// The reference has two sources. Everything a command declares — usage line,
// descriptions, examples, flags and subcommands — comes from the command tree,
// so it cannot drift from the binary. Semantics that do not belong in --help
// (exit-status tables, lifecycle explanations, replay caveats) live in
// hand-written notes under docs/cli/notes/, one file per command path, which
// are included verbatim after that command's generated section.
package clidocs

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// IntroNote is the notes file included verbatim before the command sections.
const IntroNote = "_intro.md"

// Header marks the reference as generated output.
const Header = "<!-- Code generated by `go run ./internal/clidocs/gen`; DO NOT EDIT. -->\n"

// Render produces the CLI reference for root. notes holds the hand-written
// notes files; a notes file that names no command is an error, so notes cannot
// outlive the command they describe.
func Render(root *cobra.Command, notes fs.FS) ([]byte, error) {
	commands := documentedCommands(root)
	known := make(map[string]bool, len(commands))
	for _, c := range commands {
		known[NoteName(c)] = true
	}
	if err := checkNotes(notes, known); err != nil {
		return nil, err
	}

	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("\n# CLI Reference\n\n")
	b.WriteString("This file is generated from the command tree. Edit command help in `cmd/`\n")
	b.WriteString("and hand-written notes in `docs/cli/notes/`, then run `make docs`.\n")
	b.WriteString("`pudl help --json` prints the same tree in machine-readable form.\n\n")
	if err := writeNote(&b, notes, IntroNote); err != nil {
		return nil, err
	}

	writeGlobalFlags(&b, root)
	writeIndex(&b, commands)
	for _, c := range commands {
		writeCommand(&b, c)
		if err := writeNote(&b, notes, NoteName(c)); err != nil {
			return nil, err
		}
	}
	return bytes.TrimRight(b.Bytes(), "\n"), nil
}

// NoteName is the notes file for a command: its path below the root joined
// with underscores, e.g. "run_set.md" for `pudl run set`.
func NoteName(c *cobra.Command) string {
	path := strings.Fields(c.CommandPath())[1:]
	return strings.Join(path, "_") + ".md"
}

// documentedCommands returns every visible command below root, depth-first in
// name order.
func documentedCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, child := range sortedChildren(c) {
			out = append(out, child)
			walk(child)
		}
	}
	walk(root)
	return out
}

func sortedChildren(c *cobra.Command) []*cobra.Command {
	var children []*cobra.Command
	for _, child := range c.Commands() {
		if child.Hidden || child.Deprecated != "" || child.Name() == "help" {
			continue
		}
		children = append(children, child)
	}
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	return children
}

func checkNotes(notes fs.FS, known map[string]bool) error {
	entries, err := fs.ReadDir(notes, ".")
	if err != nil {
		return fmt.Errorf("read notes: %w", err)
	}
	var stale []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".md") || name == IntroNote {
			continue
		}
		if !known[name] {
			stale = append(stale, name)
		}
	}
	if len(stale) > 0 {
		return fmt.Errorf("notes name no documented command (rename or delete them): %s", strings.Join(stale, ", "))
	}
	return nil
}

func writeNote(b *bytes.Buffer, notes fs.FS, name string) error {
	data, err := fs.ReadFile(notes, name)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read note %s: %w", name, err)
	}
	b.Write(bytes.TrimSpace(data))
	b.WriteString("\n\n")
	return nil
}

func writeGlobalFlags(b *bytes.Buffer, root *cobra.Command) {
	flags := visibleFlags(root.PersistentFlags())
	if len(flags) == 0 {
		return
	}
	b.WriteString("## Global flags\n\n")
	b.WriteString("These flags apply to every command.\n\n")
	writeFlagTable(b, flags)
}

func writeIndex(b *bytes.Buffer, commands []*cobra.Command) {
	b.WriteString("## Commands\n\n")
	for _, c := range commands {
		depth := len(strings.Fields(c.CommandPath())) - 2
		fmt.Fprintf(b, "%s- [%s](#%s) — %s\n", strings.Repeat("  ", depth), c.CommandPath(), anchor(c), c.Short)
	}
	b.WriteString("\n")
}

func writeCommand(b *bytes.Buffer, c *cobra.Command) {
	fmt.Fprintf(b, "## %s\n\n", c.CommandPath())
	if c.Short != "" {
		fmt.Fprintf(b, "%s\n\n", c.Short)
	}
	if c.Runnable() {
		fmt.Fprintf(b, "```text\n%s\n```\n\n", c.UseLine())
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
		fmt.Fprintf(b, "```text\n%s\n```\n\n", long)
	}
	if ex := strings.TrimSpace(c.Example); ex != "" {
		fmt.Fprintf(b, "Examples:\n\n```bash\n%s\n```\n\n", ex)
	}
	if flags := commandFlags(c); len(flags) > 0 {
		b.WriteString("Flags:\n\n")
		writeFlagTable(b, flags)
	}
	if children := sortedChildren(c); len(children) > 0 {
		b.WriteString("Subcommands:\n\n")
		for _, child := range children {
			fmt.Fprintf(b, "- [%s](#%s) — %s\n", child.CommandPath(), anchor(child), child.Short)
		}
		b.WriteString("\n")
	}
}

// commandFlags is a command's own flags plus those it inherits from a parent
// other than the root, whose persistent flags are documented once as global.
func commandFlags(c *cobra.Command) []*pflag.Flag {
	global := map[string]bool{}
	c.Root().PersistentFlags().VisitAll(func(f *pflag.Flag) { global[f.Name] = true })
	byName := map[string]*pflag.Flag{}
	add := func(fs *pflag.FlagSet) {
		for _, f := range visibleFlags(fs) {
			if !global[f.Name] {
				byName[f.Name] = f
			}
		}
	}
	add(c.LocalFlags())
	add(c.InheritedFlags())
	out := make([]*pflag.Flag, 0, len(byName))
	for _, f := range byName {
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func visibleFlags(fs *pflag.FlagSet) []*pflag.Flag {
	var out []*pflag.Flag
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Deprecated != "" || f.Name == "help" {
			return
		}
		out = append(out, f)
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func writeFlagTable(b *bytes.Buffer, flags []*pflag.Flag) {
	b.WriteString("| Flag | Type | Default | Description |\n")
	b.WriteString("|------|------|---------|-------------|\n")
	for _, f := range flags {
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", name, f.Value.Type(), defaultCell(f), cell(f.Usage))
	}
	b.WriteString("\n")
}

func defaultCell(f *pflag.Flag) string {
	switch f.DefValue {
	case "", "[]", "false", "0", "0s":
		return ""
	}
	return "`" + f.DefValue + "`"
}

// cell makes text safe inside a Markdown table cell. Angle brackets are
// escaped only outside backtick code spans, where entities would render
// literally.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)
	parts := strings.Split(s, "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = strings.ReplaceAll(parts[i], "<", "&lt;")
		parts[i] = strings.ReplaceAll(parts[i], ">", "&gt;")
	}
	return strings.Join(parts, "`")
}

// anchor reproduces GitHub's heading anchor for "## pudl run set".
func anchor(c *cobra.Command) string {
	return strings.ReplaceAll(strings.ToLower(c.CommandPath()), " ", "-")
}
