package mubridge

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/chazu/pudl/internal/muschemas"
)

// PluginInstallRequiredError is returned when PUDL needs a catalog-installed
// plugin but its extracted bundle or package metadata is unavailable.
type PluginInstallRequiredError struct {
	Name    string
	Version string
	Reason  string
}

func (e *PluginInstallRequiredError) Error() string {
	ref := e.Name
	if e.Version != "" {
		ref += "@" + e.Version
	}
	message := fmt.Sprintf("mu plugin %q is not available", ref)
	if e.Reason != "" {
		message += ": " + e.Reason
	}
	return message + "; run `mu plugin install " + ref + "`"
}

type muLockFile struct {
	SchemaVersion int              `json:"schema_version"`
	Plugins       []muLockedPlugin `json:"plugins"`
}

type muLockedPlugin struct {
	Name         string             `json:"name"`
	Version      string             `json:"version"`
	BundleDigest string             `json:"bundle_digest"`
	Schemas      []PluginSchemaDecl `json:"schemas,omitempty"`
	PUDLMappings []PluginMapping    `json:"pudl_mappings,omitempty"`
}

type installedPluginMetadata struct {
	Name         string             `json:"name"`
	Version      string             `json:"version"`
	BundleDigest string             `json:"bundle_digest"`
	Schemas      []PluginSchemaDecl `json:"schemas,omitempty"`
	PUDLMappings []PluginMapping    `json:"pudl_mappings,omitempty"`
}

// InstalledPluginBundleDir resolves the stable extracted-bundle path used by
// mu's CAS resolver. The digest is full or short sha256; only the first 12
// hex characters form the on-disk bundle suffix.
func InstalledPluginBundleDir(name, digest string) (string, error) {
	if strings.TrimSpace(name) == "" || strings.ContainsAny(name, `/\\`) {
		return "", fmt.Errorf("invalid mu plugin name %q", name)
	}
	hash := strings.TrimPrefix(strings.TrimSpace(digest), "sha256:")
	if len(hash) < 12 {
		return "", fmt.Errorf("invalid mu plugin digest %q", digest)
	}
	if _, err := hex.DecodeString(hash); err != nil {
		return "", fmt.Errorf("invalid mu plugin digest %q: %w", digest, err)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate mu plugin cache: %w", err)
	}
	bundle := filepath.Join(home, ".mu", "plugins", name, "bundle-"+hash[:12])
	info, err := os.Stat(bundle)
	if os.IsNotExist(err) {
		return "", fmt.Errorf("bundle %q is not extracted", digest)
	}
	if err != nil {
		return "", fmt.Errorf("inspect plugin bundle: %w", err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("plugin bundle %q is not a directory", bundle)
	}
	return bundle, nil
}

// LoadInstalledPluginPackage reads metadata generated by mu plugin install.
// The cache-side file is preferred because it also supports ad-hoc PUDL runs
// outside the project that owns mu.lock; the lockfile is the project fallback.
func LoadInstalledPluginPackage(projectRoot, name, digest string) (PluginPackage, string, error) {
	locked, lockErr := loadLockedPlugin(projectRoot, name, digest)
	if lockErr != nil && !os.IsNotExist(lockErr) {
		return PluginPackage{}, "", lockErr
	}
	bundle, bundleErr := InstalledPluginBundleDir(name, digest)
	if bundleErr != nil {
		version := ""
		if locked != nil {
			version = locked.Version
		}
		return PluginPackage{}, "", &PluginInstallRequiredError{Name: name, Version: version, Reason: bundleErr.Error()}
	}

	metadataPath := filepath.Join(bundle, "mu-plugin.json")
	if data, err := os.ReadFile(metadataPath); err == nil {
		var metadata installedPluginMetadata
		if err := json.Unmarshal(data, &metadata); err != nil {
			return PluginPackage{}, "", fmt.Errorf("decode installed plugin metadata %s: %w", metadataPath, err)
		}
		if metadata.Name != "" && metadata.Name != name {
			return PluginPackage{}, "", fmt.Errorf("installed plugin metadata names %q, requested %q", metadata.Name, name)
		}
		return PluginPackage{Schemas: metadata.Schemas, Mappings: metadata.PUDLMappings}, bundle, nil
	} else if !os.IsNotExist(err) {
		return PluginPackage{}, "", fmt.Errorf("read installed plugin metadata %s: %w", metadataPath, err)
	}

	if locked != nil {
		return PluginPackage{Schemas: locked.Schemas, Mappings: locked.PUDLMappings}, bundle, nil
	}
	if _, err := os.Stat(filepath.Join(bundle, "mu.cue")); err == nil {
		pkg, err := LoadPluginPackage(bundle)
		return pkg, bundle, err
	}
	return PluginPackage{}, "", &PluginInstallRequiredError{
		Name:   name,
		Reason: "installed bundle has no package metadata",
	}
}

// SyncInstalledPluginSchemas imports the package-owned schemas from an
// installed bundle into PUDL's append-only cache and returns its mappings.
func SyncInstalledPluginSchemas(cache *muschemas.Cache, projectRoot, name, digest string) (PluginPackage, error) {
	if cache == nil {
		return PluginPackage{}, fmt.Errorf("schema cache is required")
	}
	pkg, bundle, err := LoadInstalledPluginPackage(projectRoot, name, digest)
	if err != nil {
		return PluginPackage{}, err
	}
	if err := syncPluginPackage(cache, bundle, pkg); err != nil {
		return PluginPackage{}, err
	}
	return pkg, nil
}

func loadLockedPlugin(projectRoot, name, digest string) (*muLockedPlugin, error) {
	if projectRoot == "" {
		return nil, nil
	}
	data, err := os.ReadFile(filepath.Join(projectRoot, "mu.lock"))
	if err != nil {
		return nil, err
	}
	var lock muLockFile
	if err := json.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("decode mu.lock: %w", err)
	}
	if lock.SchemaVersion != 1 {
		return nil, fmt.Errorf("mu.lock schema_version %d is unsupported", lock.SchemaVersion)
	}
	for i := range lock.Plugins {
		plugin := &lock.Plugins[i]
		if plugin.Name != name {
			continue
		}
		if digest != "" && !sameBundleDigest(plugin.BundleDigest, digest) {
			return nil, fmt.Errorf("mu.lock pins %q to %s, requested %s", name, plugin.BundleDigest, digest)
		}
		return plugin, nil
	}
	return nil, nil
}

func sameBundleDigest(left, right string) bool {
	left = strings.TrimPrefix(strings.TrimSpace(left), "sha256:")
	right = strings.TrimPrefix(strings.TrimSpace(right), "sha256:")
	if len(left) < 12 || len(right) < 12 {
		return left == right
	}
	return left[:12] == right[:12]
}
